### ISSUE TITLE
Problem while running on Android API 23 or lower

### ISSUE THREAD

**Issue by felipeaugustox** [shahzadakram67/flutter_tex#1]
I'm getting the following error:

> [INFO:CONSOLE(49)] "Uncaught TypeError: Cannot read property 'get' of undefined", source: http://localhost:8080/packages/flutter_tex/MathJax/index.html?data=%0A%20%20%3Cp%3E%0A%0A%20%20%20%20A%20simple%20Example%20to%20render%20%5C(%20%5Crm%5C%5CTeX%20%5C)%20in%20flutter%3Cbr%3E%0A%0A%20%20%20%20%3Cstyle%3E%0A%20%20%20%20%20%20.card%20%7B%0A%20%20%20%20%20%20%20%20

If I run on physical device I don't receive that error.

I also receive the following message after the main error:

> W/art     ( 1753): Attempt to remove non-JNI local reference, dumping thread

Flutter 1.2.0
Genymotion Google Nexus 5 - Android API 6.0

**Comment by shahzadakram67** [comment]
Is it working fine on physical device and android emulator?

**Comment by felipeaugustox** [comment]
I made more tests, it's not working on Android API 23 or lower, on both Android and Genymotion simulators, then it's not related just to Genymotion, but to Android APIs

**Comment by Valkyrz** [comment]
I think I'm having a similar issue, the sample code runs fine on my emulator since its API 28 irrc but for my physical device, it runs Kitkat 4.4.2 and I get this line:

_"E/PlatformViewsController(15419): Trying to use platform views with API 19, required API level is: 20"_

I'm still pretty new to mobile development, more so with flutter but I'll be looking up a way around this. On my physical phone its doesn't display the formulas just the appBar with title. Any ideas or advice on how to work on this are heavily appreciated it!

**Comment by shahzadakram67** [comment]
@Valkyrz  4.4.2 is running on API 19 Please change your emulator having at least API 20,

**Comment by shahzadakram67** [comment]
I dig deep this issue, Its not problem in the package , we are facing this issue with emulator webview as I checked it on physical device at API 23 its working fine there,  If anybody has a physical device containing API 20-22 please verify this.

**Comment by shahzadakram67** [comment]
Please check latest update of the package the issue has been solved.

**Comment by felipeaugustox** [comment]
Tested here on Android API 21, it's working now, thanks!
